<html xmlns:string="xalan://java.lang.String" xmlns:lxslt="http://xml.apache.org/xslt">
<head>
<META http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Standard Output from CategorySuite</title>
</head>
<body>
<pre> INFO [main] - com.salesforce.utils.datastore.FileIO:-1:Setting the Config Property Key [CurrentTestName] to Value: testAddANewAccount_Sales
 INFO [main] - com.salesforce.utils.datastore.MySQLConnect:-1:Database connection attempt failed! Check the stack trace.
 INFO [main] - com.salesforce.utils.datastore.MySQLConnect:-1:Database connection attempt failed! Check the stack trace.
DEBUG [main] - com.salesforce.utils.datastore.FileIO:-1:Directory: "report/images/" created
 INFO [main] - com.salesforce.utils.datastore.MySQLConnect:-1:Database connection attempt failed! Check the stack trace.
DEBUG [main] - com.salesforce.tests.functionaltests.CloudBaseTest:-1:------------------------------------------------------
 INFO [main] - com.salesforce.utils.datastore.MySQLConnect:-1:Database connection attempt failed! Check the stack trace.
DEBUG [main] - com.salesforce.tests.functionaltests.CloudBaseTest:-1:Executing Test: testAddANewAccount_Sales()...
 INFO [main] - com.salesforce.utils.datastore.MySQLConnect:-1:Database connection attempt failed! Check the stack trace.
DEBUG [main] - com.salesforce.tests.functionaltests.CloudBaseTest:-1:------------------------------------------------------
 INFO [main] - com.salesforce.utils.datastore.MySQLConnect:-1:Database connection attempt failed! Check the stack trace.
DEBUG [main] - com.salesforce.tests.functionaltests.CloudBaseTest:-1:------------------------------------------------------
 INFO [main] - com.salesforce.utils.datastore.MySQLConnect:-1:Database connection attempt failed! Check the stack trace.
DEBUG [main] - com.salesforce.tests.functionaltests.CloudBaseTest:-1:Initializing... 
 INFO [main] - com.salesforce.utils.datastore.MySQLConnect:-1:Database connection attempt failed! Check the stack trace.
DEBUG [main] - com.salesforce.tests.functionaltests.CloudBaseTest:-1:------------------------------------------------------
 INFO [main] - com.salesforce.utils.datastore.MySQLConnect:-1:Database connection attempt failed! Check the stack trace.
DEBUG [main] - com.salesforce.utils.datastore.FileIO:-1:Taking screenshot for test: "testAddANewAccount_Sales"
 INFO [main] - com.salesforce.utils.datastore.MySQLConnect:-1:Database connection attempt failed! Check the stack trace.
 INFO [main] - com.salesforce.utils.datastore.FileIO:-1:Setting the Config Property Key [CurrentTestName] to Value: testAddANewContact_Sales
 INFO [main] - com.salesforce.utils.datastore.MySQLConnect:-1:Database connection attempt failed! Check the stack trace.
 INFO [main] - com.salesforce.utils.datastore.MySQLConnect:-1:Database connection attempt failed! Check the stack trace.
DEBUG [main] - com.salesforce.utils.datastore.FileIO:-1:Directory: "report/images/" created
 INFO [main] - com.salesforce.utils.datastore.MySQLConnect:-1:Database connection attempt failed! Check the stack trace.
DEBUG [main] - com.salesforce.tests.functionaltests.CloudBaseTest:-1:------------------------------------------------------
 INFO [main] - com.salesforce.utils.datastore.MySQLConnect:-1:Database connection attempt failed! Check the stack trace.
DEBUG [main] - com.salesforce.tests.functionaltests.CloudBaseTest:-1:Executing Test: testAddANewContact_Sales()...
 INFO [main] - com.salesforce.utils.datastore.MySQLConnect:-1:Database connection attempt failed! Check the stack trace.
DEBUG [main] - com.salesforce.tests.functionaltests.CloudBaseTest:-1:------------------------------------------------------
 INFO [main] - com.salesforce.utils.datastore.MySQLConnect:-1:Database connection attempt failed! Check the stack trace.
DEBUG [main] - com.salesforce.tests.functionaltests.CloudBaseTest:-1:------------------------------------------------------
 INFO [main] - com.salesforce.utils.datastore.MySQLConnect:-1:Database connection attempt failed! Check the stack trace.
DEBUG [main] - com.salesforce.tests.functionaltests.CloudBaseTest:-1:Initializing... 
 INFO [main] - com.salesforce.utils.datastore.MySQLConnect:-1:Database connection attempt failed! Check the stack trace.
DEBUG [main] - com.salesforce.tests.functionaltests.CloudBaseTest:-1:------------------------------------------------------
 INFO [main] - com.salesforce.utils.datastore.MySQLConnect:-1:Database connection attempt failed! Check the stack trace.
DEBUG [main] - com.salesforce.utils.datastore.FileIO:-1:Taking screenshot for test: "testAddANewContact_Sales"
 INFO [main] - com.salesforce.utils.datastore.MySQLConnect:-1:Database connection attempt failed! Check the stack trace.
 INFO [main] - com.salesforce.utils.datastore.FileIO:-1:Setting the Config Property Key [CurrentTestName] to Value: testAddANewOpportunity
 INFO [main] - com.salesforce.utils.datastore.MySQLConnect:-1:Database connection attempt failed! Check the stack trace.
 INFO [main] - com.salesforce.utils.datastore.MySQLConnect:-1:Database connection attempt failed! Check the stack trace.
DEBUG [main] - com.salesforce.utils.datastore.FileIO:-1:Directory: "report/images/" created
 INFO [main] - com.salesforce.utils.datastore.MySQLConnect:-1:Database connection attempt failed! Check the stack trace.
DEBUG [main] - com.salesforce.tests.functionaltests.CloudBaseTest:-1:------------------------------------------------------
 INFO [main] - com.salesforce.utils.datastore.MySQLConnect:-1:Database connection attempt failed! Check the stack trace.
DEBUG [main] - com.salesforce.tests.functionaltests.CloudBaseTest:-1:Executing Test: testAddANewOpportunity()...
 INFO [main] - com.salesforce.utils.datastore.MySQLConnect:-1:Database connection attempt failed! Check the stack trace.
DEBUG [main] - com.salesforce.tests.functionaltests.CloudBaseTest:-1:------------------------------------------------------
 INFO [main] - com.salesforce.utils.datastore.MySQLConnect:-1:Database connection attempt failed! Check the stack trace.
DEBUG [main] - com.salesforce.tests.functionaltests.CloudBaseTest:-1:------------------------------------------------------
 INFO [main] - com.salesforce.utils.datastore.MySQLConnect:-1:Database connection attempt failed! Check the stack trace.
DEBUG [main] - com.salesforce.tests.functionaltests.CloudBaseTest:-1:Initializing... 
 INFO [main] - com.salesforce.utils.datastore.MySQLConnect:-1:Database connection attempt failed! Check the stack trace.
DEBUG [main] - com.salesforce.tests.functionaltests.CloudBaseTest:-1:------------------------------------------------------
 INFO [main] - com.salesforce.utils.datastore.MySQLConnect:-1:Database connection attempt failed! Check the stack trace.
DEBUG [main] - com.salesforce.utils.datastore.FileIO:-1:Taking screenshot for test: "testAddANewOpportunity"
 INFO [main] - com.salesforce.utils.datastore.MySQLConnect:-1:Database connection attempt failed! Check the stack trace.
</pre>
</body>
</html>
